spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size : 1000

  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#server:
#  port: port